name: Access Repository Secret

on:
  push:
    branches:
      - main

jobs:
  access-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Access Secret
        run: |
          echo "The secret value is ${{ secrets.DEFAULT_EMAIL }}"
